library(lme4)
library(testthat)
fm1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)
expect_equal(colnames(model.frame(fm1)),c("Reaction","Days","Subject"))
expect_equal(colnames(model.frame(fm1,fixed.only=TRUE)),c("Reaction","Days"))
expect_equal(formula(fm1),Reaction ~ Days + (Days | Subject))
expect_equal(formula(fm1,fixed.only=TRUE),Reaction ~ Days)
