FROM rocker/r-bspm:jammy

## pull the lme4 repo
## R CMD build --compact-vignettes=both lme4
## ping CRAN to figure out the current CRAN version number
## ping DESCRIPTION to figure out the current GitHub version number
## wget the current version (or R -> download.file())
## run machinery as specified by checkReverse, checkChanges

## option to install only? (e.g. to run in an interactive session on SHARCnet to install needed pkgs)
