// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// RSCupdate
void RSCupdate(const MiMat rv, const MMat xv, const MVec theta, MSpMat m);
RcppExport SEXP lme4_RSCupdate(SEXP rvSEXP, SEXP xvSEXP, SEXP thetaSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    MiMat rv = Rcpp::as<MiMat >(rvSEXP);
    MMat xv = Rcpp::as<MMat >(xvSEXP);
    MVec theta = Rcpp::as<MVec >(thetaSEXP);
    MSpMat m = Rcpp::as<MSpMat >(mSEXP);
    RSCupdate(rv, xv, theta, m);
    return R_NilValue;
END_RCPP
}
