// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "RSC.h"

using namespace Rcpp;

// RSCupdate
RcppExport SEXP lme4_RSCupdate(SEXP rvSEXP, SEXP xvSEXP, SEXP thetaSEXP, SEXP lowerSEXP, SEXP residSEXP, SEXP ASEXP, SEXP ubetaSEXP) {
BEGIN_RCPP
    IntegerMatrix rv = Rcpp::as<IntegerMatrix >(rvSEXP);
    NumericMatrix xv = Rcpp::as<NumericMatrix >(xvSEXP);
    NumericVector theta = Rcpp::as<NumericVector >(thetaSEXP);
    NumericVector lower = Rcpp::as<NumericVector >(lowerSEXP);
    NumericVector resid = Rcpp::as<NumericVector >(residSEXP);
    S4 A = Rcpp::as<S4 >(ASEXP);
    NumericVector ubeta = Rcpp::as<NumericVector >(ubetaSEXP);
    RSC rr(rv, xv, lower);
    rr.update_A(theta, resid, A, ubeta);
    return R_NilValue;
END_RCPP
}
