// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// RSCupdate
void RSCupdate(const IntegerMatrix rv, const NumericMatrix xv, const List vc, S4 m);
RcppExport SEXP lme4_RSCupdate(SEXP rvSEXP, SEXP xvSEXP, SEXP vcSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    IntegerMatrix rv = Rcpp::as<IntegerMatrix >(rvSEXP);
    NumericMatrix xv = Rcpp::as<NumericMatrix >(xvSEXP);
    List vc = Rcpp::as<List >(vcSEXP);
    S4 m = Rcpp::as<S4 >(mSEXP);
    RSCupdate(rv, xv, vc, m);
    return R_NilValue;
END_RCPP
}
