# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update for the penalized least squares problem
#' 
#' @param rv the matrix of row indices for the regular sparse column representation of ZtXt
#' @param xv the non-zero values in ZtXt
#' @param theta vector of relative standard deviations
#' @param m the sparse matrix to be updated.  Must have the correct pattern.
RSCupdate <- function(rv, xv, theta, m) {
    invisible(.Call('lme4_RSCupdate', PACKAGE = 'lme4', rv, xv, theta, m))
}

