# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update for the penalized least squares problem
#' 
#' @param rv the matrix of row indices for the regular sparse column representation of ZtXt
#' @param xv the non-zero values in ZtXt
#' @param theta vector of relative standard deviations
#' @param m the sparse matrix to be updated.  Must have the correct pattern.
#' @examples
#' rv <- rbind(as.integer(Dyestuff$Batch) - 1L, 6L)
#' xv <- matrix(1, nrow=nrow(rv), ncol=ncol(rv)
#' A <- sparseMatrix(i=as.integer(c(1,1,2,2,3,3,4,4,5,5,6,6,7)),
#'                   j=as.integer(c(1,7,2,7,3,7,4,7,5,7,6,7,7)),
#'                   x=rep.int(1.,13L), symmetric=TRUE,check=FALSE)
#' RSCupdate(rv, xv, 0.831, A)
#' A
RSCupdate <- function(rv, xv, theta, m) {
    invisible(.Call('lme4_RSCupdate', PACKAGE = 'lme4', rv, xv, theta, m))
}

