# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
# https://github.com/marketplace/actions/ci-skip-action
on:
  workflow_dispatch
#  push:
#    branches:
#      - main
#      - master

name: pkgdown

jobs:
  pkgdown:
 #   if: "contains(github.event.head_commit.message, '[rebuild site]')"
 #   runs-on: macOS-latest
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      ## attempt to control over-parallelization
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
#      - name: textshaping dependencies for MacOS
# for some reason we insist on installing newer version of textshaping from source, so we need these ...
#        run: brew install harfbuzz fribidi
      - name: textshaping dependencies for LInux
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      - name: Install pkgdown.extras and remotes
        run: |
          ## (ragg install fails downstream, missing these packages ...??)
          install.packages(c("systemfonts", "textshaping","pkgdown","ragg","devtools"))
          install.packages('remotes')
          remotes::install_github("HenrikBengtsson/pkgdown.extras")
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::Matrix, any::xfun, pkgdown.extras=?ignore
          needs: check
          upgrade: 'TRUE'

      - name: Install LaTeX and extras
        if: runner.os == 'Linux'
        run: sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra

      # - name: Install extra LaTeX dependencies
      #   run: |  # I know remotes is duplicated, but takes little time and better if we want to copy-paste workflows..
      #     install.packages(c("remotes", "devtools"))
      #     remotes::install_deps(dependencies = TRUE)
      #     install.packages('tinytex')
      #     tinytex::install_tinytex(force=TRUE) ## force = TRUE?
      #     tinytex::tlmgr_install("koma-script") # for scrtime.sty
      #     tinytex::tlmgr_install("amscls")      # for amsthm.sty
      #     tinytex::tlmgr_install(c("multirow","colortbl","siunitx","setspace"))
      #     tinytex::tlmgr_install(c("lineno","fancyhdr","ulem","caption"))
      #     tinytex::tlmgr_install("babel-english")
      #     tinytex::tlmgr_install("pgf") # tikz
      #     tinytex::tlmgr_install(c("placeins","lastpage","cleveref","listings","threeparttable","wrapfig","adjustbox","hyperref","tabularx","collectbox"))
      #   shell: Rscript {0}
      - name: Install lme4
        run: devtools::install()
        shell: Rscript {0}
      - name: Convert NEWS
        run: |
          xfun::news2md("lme4", output = "NEWS.md", category = TRUE)
        shell: Rscript {0}
      - name: Rebuild site 
        run: |
          pkgdown.extras::build_site(preview=FALSE)
        shell: Rscript {0}
      - name: Commit site
        run: |
          git config --global user.name 'pkgdown-bot'
          git config --global user.email 'pkgdown-bot@users.noreply.github.com'
          git add --all
          git commit -am "Site rebuild [skip ci]"
          git push
